export const CLUSTERS = {
  'Sweet Basil': 1,
  'Thai Basil': 1,
  'Holy Basil': 1,
  Peppermint: 4,
  Spearmint: 0,
  Tarragon: 0,
  'Green Tea': 0,
  Stevia: 2,
  Thyme: 3,
  Serpentina: 0,
  'Damong Maria': 0,
  Oregano: 2,
  Mansanilya: 4,
  'Sabah Snake Grass': 3,
  'Blue Ternate': 3,
  Taheebo: 3,
  Sambong: 3,
  Cranberry: 2,
  Lagundi: 3,
  'Lemon Grass': 2,
  Lubigan: 3,
  Parsley: 3,
  'Gotu Kola': 3,
  Sage: 2,
  Rosemary: 2,
  'Citronella Malvarosa': 3,
  Dill: 0,
  Cilantro: 2,
  'Vanilla Plant': 3,
};

export const cluster0 = [
  'Spearmint',
  'Tarragon',
  'Green Tea',
  'Serpentina',
  'Damong Maria',
  'Dill',
];
export const cluster1 = ['Sweet Basil', 'Thai Basil', 'Holy Basil'];
export const cluster2 = [
  'Stevia',
  'Oregano',
  'Cranberry',
  'Lemon Grass',
  'Sage',
  'Rosemary',
  'Cilantro',
];
export const cluster3 = [
  'Thyme',
  'Sabah Snake Grass',
  'Blue Ternate',
  'Taheebo',
  'Sambong',
  'Lagundi',
  'Lubigan',
  'Parsley',
  'Gotu Kola',
  'Citronella Malvarosa',
  'Vanilla Plant',
];
export const cluster4 = ['Peppermint', 'Mansanilya'];
