export const ROUTES = {
  LANDING_SCREEN: 'LANDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  PLANT_DICTIONARY_SCREEN: 'PLANT_DICTIONARY_SCREEN',
  PLANT_RECORD_SCREEN: 'PLANT_RECORD_SCREEN',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  TERMS_SCREEN: 'TERMS_SCREEN',
  CONTACT_US_SCREEN: 'CONTACT_US_SCREEN',
  SUGGESTION_SCREEN: 'SUGGESTION_SCREEN',
  PLANT_SUGGESTION_SCREEN: 'PLANT_SUGGESTION_SCREEN',
};
