export const ROUTES = {
  LANDING_SCREEN: 'LANDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  PLANT_DICTIONARY_SCREEN: 'PLANT_DICTIONARY_SCREEN',
  PLANT_RECORD_SCREEN: 'PLANT_RECORD_SCREEN',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
};
